/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerOrdersRouteImport } from './routes/customer.orders'
import { Route as CustomerProductsRouteImport } from './routes/customer.products'
import { Route as CustomerWishlistRouteImport } from './routes/customer.wishlist'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password.verify'
import { Route as SellerDashboardRouteImport } from './routes/seller.dashboard'
import { Route as SellerOrdersRouteImport } from './routes/seller.orders'
import { Route as SellerProductsRouteImport } from './routes/seller.products'
import { Route as SellerProfileRouteImport } from './routes/seller.profile'
import { Route as CustomerCheckoutCancelRouteImport } from './routes/customer.checkout.cancel'
import { Route as CustomerCheckoutSuccessRouteImport } from './routes/customer.checkout.success'
import { Route as CustomerProductsIndexRouteImport } from './routes/customer.products.index'
import { Route as CustomerProductsProductIdRouteImport } from './routes/customer.products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/customer/cart',
  path: '/customer/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/customer/checkout',
  path: '/customer/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersRoute = CustomerOrdersRouteImport.update({
  id: '/customer/orders',
  path: '/customer/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProductsRoute = CustomerProductsRouteImport.update({
  id: '/customer/products',
  path: '/customer/products',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/customer/wishlist',
  path: '/customer/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const SellerDashboardRoute = SellerDashboardRouteImport.update({
  id: '/seller/dashboard',
  path: '/seller/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerOrdersRoute = SellerOrdersRouteImport.update({
  id: '/seller/orders',
  path: '/seller/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProductsRoute = SellerProductsRouteImport.update({
  id: '/seller/products',
  path: '/seller/products',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerProfileRoute = SellerProfileRouteImport.update({
  id: '/seller/profile',
  path: '/seller/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCheckoutCancelRoute = CustomerCheckoutCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => CustomerCheckoutRoute,
} as any)
const CustomerCheckoutSuccessRoute = CustomerCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CustomerCheckoutRoute,
} as any)
const CustomerProductsIndexRoute = CustomerProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerProductsRoute,
} as any)
const CustomerProductsProductIdRoute =
  CustomerProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => CustomerProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRouteWithChildren
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/products': typeof CustomerProductsRouteWithChildren
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/customer/checkout/cancel': typeof CustomerCheckoutCancelRoute
  '/customer/checkout/success': typeof CustomerCheckoutSuccessRoute
  '/customer/products/$productId': typeof CustomerProductsProductIdRoute
  '/customer/products/': typeof CustomerProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRouteWithChildren
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/customer/checkout/cancel': typeof CustomerCheckoutCancelRoute
  '/customer/checkout/success': typeof CustomerCheckoutSuccessRoute
  '/customer/products/$productId': typeof CustomerProductsProductIdRoute
  '/customer/products': typeof CustomerProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRouteWithChildren
  '/customer/orders': typeof CustomerOrdersRoute
  '/customer/products': typeof CustomerProductsRouteWithChildren
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/seller/dashboard': typeof SellerDashboardRoute
  '/seller/orders': typeof SellerOrdersRoute
  '/seller/products': typeof SellerProductsRoute
  '/seller/profile': typeof SellerProfileRoute
  '/customer/checkout/cancel': typeof CustomerCheckoutCancelRoute
  '/customer/checkout/success': typeof CustomerCheckoutSuccessRoute
  '/customer/products/$productId': typeof CustomerProductsProductIdRoute
  '/customer/products/': typeof CustomerProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/orders'
    | '/customer/products'
    | '/customer/wishlist'
    | '/forgot-password/verify'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/customer/checkout/cancel'
    | '/customer/checkout/success'
    | '/customer/products/$productId'
    | '/customer/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/orders'
    | '/customer/wishlist'
    | '/forgot-password/verify'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/customer/checkout/cancel'
    | '/customer/checkout/success'
    | '/customer/products/$productId'
    | '/customer/products'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/forgot-password'
    | '/login'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/verify'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/users'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/orders'
    | '/customer/products'
    | '/customer/wishlist'
    | '/forgot-password/verify'
    | '/seller/dashboard'
    | '/seller/orders'
    | '/seller/products'
    | '/seller/profile'
    | '/customer/checkout/cancel'
    | '/customer/checkout/success'
    | '/customer/products/$productId'
    | '/customer/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ForgotPasswordRoute: typeof ForgotPasswordRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRouteWithChildren
  CustomerOrdersRoute: typeof CustomerOrdersRoute
  CustomerProductsRoute: typeof CustomerProductsRouteWithChildren
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  SellerDashboardRoute: typeof SellerDashboardRoute
  SellerOrdersRoute: typeof SellerOrdersRoute
  SellerProductsRoute: typeof SellerProductsRoute
  SellerProfileRoute: typeof SellerProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/customer/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/customer/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders': {
      id: '/customer/orders'
      path: '/customer/orders'
      fullPath: '/customer/orders'
      preLoaderRoute: typeof CustomerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/products': {
      id: '/customer/products'
      path: '/customer/products'
      fullPath: '/customer/products'
      preLoaderRoute: typeof CustomerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/wishlist': {
      id: '/customer/wishlist'
      path: '/customer/wishlist'
      fullPath: '/customer/wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/seller/dashboard': {
      id: '/seller/dashboard'
      path: '/seller/dashboard'
      fullPath: '/seller/dashboard'
      preLoaderRoute: typeof SellerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/orders': {
      id: '/seller/orders'
      path: '/seller/orders'
      fullPath: '/seller/orders'
      preLoaderRoute: typeof SellerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/products': {
      id: '/seller/products'
      path: '/seller/products'
      fullPath: '/seller/products'
      preLoaderRoute: typeof SellerProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/profile': {
      id: '/seller/profile'
      path: '/seller/profile'
      fullPath: '/seller/profile'
      preLoaderRoute: typeof SellerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/checkout/cancel': {
      id: '/customer/checkout/cancel'
      path: '/cancel'
      fullPath: '/customer/checkout/cancel'
      preLoaderRoute: typeof CustomerCheckoutCancelRouteImport
      parentRoute: typeof CustomerCheckoutRoute
    }
    '/customer/checkout/success': {
      id: '/customer/checkout/success'
      path: '/success'
      fullPath: '/customer/checkout/success'
      preLoaderRoute: typeof CustomerCheckoutSuccessRouteImport
      parentRoute: typeof CustomerCheckoutRoute
    }
    '/customer/products/': {
      id: '/customer/products/'
      path: '/'
      fullPath: '/customer/products/'
      preLoaderRoute: typeof CustomerProductsIndexRouteImport
      parentRoute: typeof CustomerProductsRoute
    }
    '/customer/products/$productId': {
      id: '/customer/products/$productId'
      path: '/$productId'
      fullPath: '/customer/products/$productId'
      preLoaderRoute: typeof CustomerProductsProductIdRouteImport
      parentRoute: typeof CustomerProductsRoute
    }
  }
}

interface ForgotPasswordRouteChildren {
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
}

const ForgotPasswordRouteChildren: ForgotPasswordRouteChildren = {
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
}

const ForgotPasswordRouteWithChildren = ForgotPasswordRoute._addFileChildren(
  ForgotPasswordRouteChildren,
)

interface CustomerCheckoutRouteChildren {
  CustomerCheckoutCancelRoute: typeof CustomerCheckoutCancelRoute
  CustomerCheckoutSuccessRoute: typeof CustomerCheckoutSuccessRoute
}

const CustomerCheckoutRouteChildren: CustomerCheckoutRouteChildren = {
  CustomerCheckoutCancelRoute: CustomerCheckoutCancelRoute,
  CustomerCheckoutSuccessRoute: CustomerCheckoutSuccessRoute,
}

const CustomerCheckoutRouteWithChildren =
  CustomerCheckoutRoute._addFileChildren(CustomerCheckoutRouteChildren)

interface CustomerProductsRouteChildren {
  CustomerProductsProductIdRoute: typeof CustomerProductsProductIdRoute
  CustomerProductsIndexRoute: typeof CustomerProductsIndexRoute
}

const CustomerProductsRouteChildren: CustomerProductsRouteChildren = {
  CustomerProductsProductIdRoute: CustomerProductsProductIdRoute,
  CustomerProductsIndexRoute: CustomerProductsIndexRoute,
}

const CustomerProductsRouteWithChildren =
  CustomerProductsRoute._addFileChildren(CustomerProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ForgotPasswordRoute: ForgotPasswordRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRouteWithChildren,
  CustomerOrdersRoute: CustomerOrdersRoute,
  CustomerProductsRoute: CustomerProductsRouteWithChildren,
  CustomerWishlistRoute: CustomerWishlistRoute,
  SellerDashboardRoute: SellerDashboardRoute,
  SellerOrdersRoute: SellerOrdersRoute,
  SellerProductsRoute: SellerProductsRoute,
  SellerProfileRoute: SellerProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
